version: "3.9"

services:
  db:
    image: postgres:14
    restart: always
    container_name: reservas_db
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    env_file:
      - .env
    container_name: reservas_app
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    depends_on:
      - db
    ports:
      - "8000:8000"

volumes:
  pgdata:
